### ISSUE TITLE
MockWebServer initialization problem

### ISSUE THREAD

**Issue by tir38** [andrzejchm/RESTMock#81]
I have a test setup something like:

```
@RunWith(AndroidJUnit4.class)
public class SomeTest {

    @Before
    public void setUp() {
        AndroidAssetsFileParser restMockFileParser 
                = new AndroidAssetsFileParser(InstrumentationRegistry.getContext());
        RESTMockServerStarter.startSync(restMockFileParser);

 ...
```

I'm getting the following error when running any test

> java.lang.NoSuchMethodError: No static method initializeInstanceForTests()V in class Lokhttp3/internal/Internal; or its super classes (declaration of 'okhttp3.internal.Internal' appears in /data/app/com.example.debug-1/base.apk)

I already have my proguard keeping everything in my test apk:

```
-dontnote **
-dontobfuscate

# hacky way to tell proguard to keep EVERYTHING
-keep class !non.existant.package.** { *; }
-dontwarn !non.existant.package.**,**
```

I can see the `initializeInstanceForTests` method in the test apk:

<img width="541" alt="test_apk" src="https://user-images.githubusercontent.com/1980553/40945852-6cede6bc-6828-11e8-8b0c-392dc71b075b.png">

However the method has been stripped from my app apk. This is expected since it isn't used in the app.

<img width="537" alt="app_apk" src="https://user-images.githubusercontent.com/1980553/40945858-743d77c0-6828-11e8-9822-006fb9c0faa9.png">

I can solve my problem by telling proguard to keep `Internal` in my **app** apk:

```
-keepclassmembers public class okhttp3.internal.Internal{
    *;
}
```

But why does this work? 

I can follow the stack trace but everything looks like it shoiuld be happening in the **test** apk.

```
RESTMockServerStarter.startSync(restMockFileParser);

// produces the callstack:

// RESTMockServer.init(mocksFileParser, logger);
// ...
// RESTMockServer.mockWebServer = new MockWebServer();
// ...
// Internal.initializeInstanceForTests();

```

Why/how is `RestMock` setting up `MockWebServer` in my app apk not in my test apk?

**Comment by andrzejchm** [comment]
this issue is entirely related with okhttp3, which recognizes the app being run under tests and wants to initialize itself for tests. Unfortunately, if you want to test a proguarded version of the app you either have to add this line you mentioned to your proguard rules, or have two different buildTypes one for testing and one for production code. Testing buld type could use a different proguard file that inherits from the release proguard file and adds this single line you've mentioned. Honestly I wouldn't care that much and stick to single buildType and one proguard file as this seems not to be a security breach and is roughly a single method to keep from okhttp3 which is open source anyway

**Comment by tir38** [comment]
I wasn't sure if this was an OkHttp issue or RestMock. I figured I'd start asking here. I agree. A separate build type is a lot of overhead just to save a single line in Proguard. Thanks for the fast response.
